---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Piracy:
    - TorrentLeech:
        - icon: https://www.torrentleech.org/images/Tl_logo-White.png
          href: https://torrentleech.org/
    - FileList:
        - icon: https://filelist.io/styles/images/logo_wood.png
          href: https://filelist.io/index.php
    - cs.rin.ru:
        - icon: https://www.userlogos.org/files/logos/jumpordie/csrinru_01.png
          href: https://cs.rin.ru/forum/
    - 1337x:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/1337x.png
          href: https://1337x.to/

- Development:
    - Github:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/github-light.svg
          href: https://github.com/

- Social:
    - Reddit:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/reddit.svg
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/youtube.svg
          href: https://youtube.com/
