- Media:
    - Plex:
        icon: https:/https://cdn.jsdelivr.net/gh/selfhst/icons/svg/plex.svg
        href: http://server.local:32400
        server: server
        container: plex
        widget:
          type: plex
          url: http://localhost:32400
          key: token # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    - Jellyfin:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/jellyfin.svg
        href: https://jellyfin.kovacs.eu.org
        server: server
        container: jellyfin
        widget:
          type: jellyfin
          url: https://jellyfin.kovacs.eu.org
          key: apiKey
          fields: ["movies", "series", "episodes"]
          enableBlocks: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false

    - Audiobookshelf:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/audiobookshelf.svg
        href: https://server.local:13378
        server: server
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://audiobookshelf:13378
          key: apikey

    - qBittorrent:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/qbittorrent.svg
        href: http://server.local:8080
        server: server
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: username
          password: password
          enableLeechProgress: true
          enableLeechSize: true

    - Sonarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/sonarr-radarr-light.svg
        href: http://server.local:8989
        server: server
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: apikey

    - Radarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/radarr.svg
        href: http://server.local:7878
        server: server
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: apikey

    - Bazarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/bazarr.svg
        href: http://server.local:6767
        server: server
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: apikey

    # - Jackett:
    #     icon: https://styles.redditmedia.com/t5_3e9ey/styles/communityIcon_vouv833bm3g31.png
    #     href: http://server.local:9117
    #     server: server
    #     container: jackett
    #     widget:
    #       type: jackett
    #       url: http://jackett:9117
    #       apikey: apikey

    - Prowlarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/prowlarr-radarr-light.svg
        href: https://prowlarr.kovacs.eu.org
        server: server
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: apikey

    - Gallery:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pigallery2-light.svg
        href: https://gallery.kovacs.eu.org
        server: server
        container: pigallery2

- Utilities:
    - Caddy:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/caddy.svg
        server: server
        container: caddy
        widget:
          type: caddy
          url: http://caddy:2019

    - AdGuard Home:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/adguard-home.svg
        href: https://dns.kovacs.eu.org
        server: server
        container: adguardhome
        widget:
          type: adguard
          url: https://dns.kovacs.eu.org
          username: user
          password: password

    - Beszel:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/beszel.svg
        href: https://beszel.kovacs.eu.org
        server: server
        container: beszel
        widget:
          type: beszel
          url: https://beszel.kovacs.eu.org
          username: username
          password: password
          systemId: idInPocketBaseDB
          version: 2

    - Portainer:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/portainer-v1.svg
        href: http://server.local:9443
        server: server
        container: portainer
        widget:
          type: portainer
          url: https://portainer:9443
          env: 2
          key: ptr_key

    - What's Up Docker:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/wud.svg
        href: https://wud.kovacs.eu.org
        server: server
        container: wud
        widget:
          type: whatsupdocker
          url: http://wud:3000

    - Scrutiny:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/scrutiny.svg
        href: https://scrutiny.kovacs.eu.org
        server: server
        container: scrutiny
        widget:
          type: scrutiny
          url: https://scrutiny.kovacs.eu.org

    - Syncthing:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/syncthing.svg
        href: http://192.168.1.158:8384
        server: server
        container: syncthing

    - File Browser:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/filebrowser-quantum.svg
        href: http://server.local:8112
        server: server
        container: file-browser

- External:
    - Uptime Kuma:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/uptime-kuma.svg
        href: https://uptime.spolai.eu
        widget:
          type: uptimekuma
          url: https://uptime.spolai.eu
          slug: server
