- Media:
    - Plex:
        icon: https:/https://cdn.jsdelivr.net/gh/selfhst/icons/svg/plex.svg
        href: http://server.local:32400
        server: server
        container: plex
        widget:
          type: plex
          url: http://localhost:32400
          key: token # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    - Audiobookshelf:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/audiobookshelf.svg
        href: https://server.local:13378
        server: server
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://audiobookshelf:13378
          key: apikey

    - qBittorrent:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/qbittorrent.svg
        href: http://server.local:8080
        server: server
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: username
          password: password

    - Sonarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/sonarr-radarr-light.svg
        href: http://server.local:8989
        server: server
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: apikey

    - Radarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/radarr.svg
        href: http://server.local:7878
        server: server
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: apikey

    - Bazarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/bazarr.svg
        href: http://server.local:6767
        server: server
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: apikey

    # - Jackett:
    #     icon: https://styles.redditmedia.com/t5_3e9ey/styles/communityIcon_vouv833bm3g31.png
    #     href: http://server.local:9117
    #     server: server
    #     container: jackett
    #     widget:
    #       type: jackett
    #       url: http://jackett:9117
    #       apikey: apikey

    - Prowlarr:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/prowlarr-radarr-light.svg
        href: https://prowlarr.kovacs.eu.org
        server: server
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: apikey

    - Gallery:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pigallery2-light.svg
        href: https://gallery.kovacs.eu.org
        server: server
        container: pigallery2

- Utilities:
    - Portainer:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/portainer-v1.svg
        href: http://server.local:9443
        server: server
        container: portainer
        widget:
          type: portainer
          url: https://portainer:9443
          env: 2
          key: ptr_key

    - Beszel:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/beszel.svg
        href: https://beszel.kovacs.eu.org
        server: server
        container: beszel
        widget:
          type: beszel
          url: https://beszel.kovacs.eu.org
          username: username
          password: password
          systemId: idInPocketBaseDB
          version: 2

    - Syncthing:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/syncthing.svg
        href: http://192.168.1.158:8384
        server: server
        container: syncthing

    - File Browser:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/filebrowser-quantum.svg
        href: http://server.local:8112
        server: server
        container: file-browser
