- Media:
    - Plex:
        icon: https://static-00.iconduck.com/assets.00/plex-icon-2048x2048-kdgfrhh9.png
        href: http://server.local:32400
        server: server
        container: plex
        widget:
          type: plex
          url: http://localhost:32400
          key: token # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    - Audiobookshelf:
        icon: https://audiobookshelf.org/Logo.png
        href: https://server.local:13378
        server: server
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://audiobookshelf:13378
          key: apikey

    - qBittorrent:
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/New_qBittorrent_Logo.svg/2048px-New_qBittorrent_Logo.svg.png
        href: http://server.local:8080
        server: server
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: username
          password: password

    - Sonarr:
        icon: https://avatars.githubusercontent.com/u/1082903?s=280&v=4
        href: http://server.local:8989
        server: server
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: apikey

    - Radarr:
        icon: https://static-00.iconduck.com/assets.00/radarr-icon-1845x2048-97le6lim.png
        href: http://server.local:7878
        server: server
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: apikey

    - Bazarr:
        icon: https://wiki.bazarr.media/img/logo.png
        href: http://server.local:6767
        server: server
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: apikey

    # - Jackett:
    #     icon: https://styles.redditmedia.com/t5_3e9ey/styles/communityIcon_vouv833bm3g31.png
    #     href: http://server.local:9117
    #     server: server
    #     container: jackett
    #     widget:
    #       type: jackett
    #       url: http://jackett:9117
    #       apikey: apikey

    - Prowlarr:
        icon: https://prowlarr.com/logo/128.png
        href: https://prowlarr.kovacs.eu.org
        server: server
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: apikey

    - Gallery:
        icon: https://media.sys.truenas.net/apps/pigallery2/icons/icon.png
        href: https://gallery.kovacs.eu.org
        server: server
        container: pigallery2

- Utilities:
    - Portainer:
        icon: https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_200,h_200/https://api.charmhub.io/api/v1/media/download/charm_Owpj9CsDEMZwVtup3ZTxxs0FtyvDqb2o_icon_5cef79c2d18f67464f39c8f2cf2d7ebb815b0071f04d3ffbb94f49fddd3ab666.png
        href: http://server.local:9443
        server: server
        container: portainer
        widget:
          type: portainer
          url: https://portainer:9443
          env: 2
          key: ptr_key

    - Beszel:
        icon: https://www.webhoop.com/wp-content/uploads/2025/03/yqpywnmjadcwmjxknneqjk4x4lrj.png
        href: https://beszel.kovacs.eu.org
        server: server
        container: beszel
        widget:
          type: beszel
          url: https://beszel.kovacs.eu.org
          username: username
          password: password
          systemId: idInPocketBaseDB
          version: 2

    - Syncthing:
        icon: https://upload.wikimedia.org/wikipedia/commons/5/57/Syncthing_Logo.svg
        href: http://192.168.1.158:8384
        server: server
        container: syncthing

    - File Browser:
        icon: https://static-00.iconduck.com/assets.00/filebrowser-icon-2048x2048-boocnon8.png
        href: http://server.local:8112
        server: server
        container: file-browser
