useEqualHeights: true
background:
  image: https://mir-s3-cdn-cf.behance.net/projects/original/897af485867481.Y3JvcCwxOTYwLDE1MzMsNjc5LDM4Mw.jpg
  opacity: 10
layout:
  Media:
    style: row
    columns: 4
  Utilities:
    style: row
    columns: 4
  External:
    style: row
    columns: 4
headerStyle: boxed
